# Floating Windows
windowrule = match:title ^(pavucontrol)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(io.github.Qalculate.qalculate-qt)$, float on
windowrule = match:class ^(.blueman-manager-wrapped)$, float on
windowrule = match:class ^(.blueman-manager-wrapped)$, size 800 600
windowrule = match:class ^(.blueman-manager-wrapped)$, center on

# Browser Picture in Picture
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on
windowrule = match:title ^(Picture-in-Picture)$, move 69.5% 4%

# XWayland Compatibility
windowrule = match:class ^(resolve)$, match:xwayland 1, no_blur on

# Keyboard Layout Viewer Rules
windowrule = match:class ^(layout-preview)$, float on
windowrule = match:class ^(layout-preview)$, center on
windowrule = match:class ^(layout-preview)$, pin on
windowrule = match:class ^(layout-preview)$, no_border on
windowrule = match:class ^(layout-preview)$, no_shadow on
windowrule = match:class ^(layout-preview)$, size 60% 60%
